// "use server";

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Layout/Navbar";
import UserContextProvider from "@/contexts/user-context";
import Loading from "@/components/UI/loading";
import { ThemeProvider, createTheme } from "@mui/material";
import ThemeMode from "@/components/UI/themeMode";
import {
  ThemeContext,
  ThemeContextProvider,
  useTheme,
} from "@/contexts/theme-context";
import { useContext } from "react";
import NavContextProvider from "@/contexts/nav-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "En-Cards",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const { theme } = useContext(ThemeContext);
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          <NavContextProvider>
            <UserContextProvider>
              <ThemeMode />
              <Navbar />
              <Loading />
              {children}
            </UserContextProvider>
          </NavContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
